name: 'ts-migration-companion-action'
description: 'GitHub Action help you to track your TypeScript Migration coverage'
author: 'swile'
branding:
  icon: check-circle
  color: green
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  master_tsc_output_path:
    description: The path to the tsc output file for master branch
    required: true
  pr_tsc_output_path:
    description: The path to the tsc output file for the pull request branch
    required: true
  tsc_rootdir:
    description: Define the root directory used by tsc
    required: false
    default: src
